version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build   # ✅ no need for export if output: 'export'

artifacts:
  base-directory: out
  files:
    - '**/*'
