version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      -cd project
      - npm install
  build:
    commands:
      - cd project
      - npm run export
  build:
    commands:
      - npm run export || echo "EXPORT FAILED"
      - echo "Listing files..."
      - ls -la
  artifacts:
    base-directory: project/out
    files:
     - '**/*'
