version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run export
      - echo "Checking out directory contents..."
      - ls -la
      - ls -la out || echo "No out folder found"
artifacts:
  base-directory: out
  files:
    - '**/*'
