version: 0.2 


phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci || npm install
  build:
    commands:
      - echo Building the React app...
      - npm run build
      - npm run export    
  post_build:
    commands:
      - echo "Listing build folder before deploy..."
      - ls -la build/
      - echo Deploying to S3...
      - aws s3 sync build/ s3://health-wellbeing-website-133/ --delete --region ap-south-1

artifacts:
  files:
    - '**/*'
  base-directory: build
