version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd project-bolt-sb1-hzpzecgy
      - npm install

  build:
    commands:
      - cd project-bolt-sb1-hzpzecgy
      - npm run export

artifacts:
  base-directory: project-bolt-sb1-hzpzecgy/out
  files:
   - '**/*'
