version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd project
      - npm install

  build:
    commands:
      - cd project
      - npm run export

artifacts:
  base-directory: project/out
  files:
   - '**/*'
